export const pals = [
  {
    id: crypto.randomUUID(),
    name: 'Lamball',
    number: '1',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'farming', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/lamball.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Cattiva',
    number: '2',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'mining', lv: '1' },
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/cattiva.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Chikipi',
    number: '3',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'farming', lv: '1' },
      { skill: 'gathering', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/chikipi.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Lifmunk',
    number: '4',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'lumbering', lv: '1' },
      { skill: 'medicineProduction', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/lifmunk.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Foxparks',
    number: '5',
    caught: '0',
    element: ['fire'],
    workSkill: [{ skill: 'kindling', lv: '1' }],
    searchFilter: [''],
    image: '/pal/icon/foxparks.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Fuack',
    number: '6',
    caught: '0',
    element: ['water'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'watering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/fuack.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Sparkit',
    number: '7',
    caught: '0',
    element: ['electric'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'generatingElectricity', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/sparkit.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Tanzee',
    number: '8',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '1' },
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'lumbering', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/tanzee.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Rooby',
    number: '9',
    caught: '0',
    element: ['fire'],
    workSkill: [{ skill: 'kindling', lv: '1' }],
    searchFilter: [''],
    image: '/pal/icon/sparkit.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Pengullet',
    number: '10',
    caught: '0',
    element: ['water', 'ice'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'watering', lv: '1' },
      { skill: 'cooling', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/pengullet.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Penking',
    number: '11',
    caught: '0',
    element: ['water', 'ice'],
    workSkill: [
      { skill: 'mining', lv: '2' },
      { skill: 'transporting', lv: '2' },
      { skill: 'watering', lv: '2' },
      { skill: 'cooling', lv: '2' },
      { skill: 'handiwork', lv: '2' },
    ],
    searchFilter: [''],
    image: '/pal/icon/sparkit.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jolthog',
    number: '12',
    caught: '0',
    element: ['electric'],
    workSkill: [{ skill: 'generatingElectricity', lv: '1' }],
    searchFilter: [''],
    image: '/pal/icon/jolthog.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jolthog Cryst',
    number: '12B',
    caught: '0',
    element: ['ice'],
    workSkill: [{ skill: 'cooling', lv: '1' }],
    searchFilter: [''],
    image: '/pal/icon/jolthogCryst.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Gumoss',
    number: '13',
    caught: '0',
    element: ['grass', 'ground'],
    workSkill: [{ skill: 'planting', lv: '1' }],
    searchFilter: [''],
    image: '/pal/icon/gumoss.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Vixy',
    number: '14',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'farming', lv: '1' },
      { skill: 'gathering', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/vixy.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Hoocrates',
    number: '15',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'gathering', lv: '1' }],
    searchFilter: [''],
    image: '/pal/icon/hoocrates.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Teafant',
    number: '16',
    caught: '0',
    element: ['water'],
    workSkill: [{ skill: 'watering', lv: '1' }],
    searchFilter: [''],
    image: '/pal/icon/teafant.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Depresso',
    number: '17',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'mining', lv: '1' },
      { skill: 'transporting', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/depresso.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Cremis',
    number: '18',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'farming', lv: '1' },
      { skill: 'gathering', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/cremis.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Daedream',
    number: '19',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/daedream.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Rushoar',
    number: '20',
    caught: '0',
    element: ['ground'],
    workSkill: [{ skill: 'mining', lv: '1' }],
    searchFilter: [''],
    image: '/pal/icon/rushoar.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Nox',
    number: '21',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'gathering', lv: '1' }],
    searchFilter: [''],
    image: '/pal/icon/nox.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Fuddler',
    number: '22',
    caught: '0',
    element: ['ground'],
    workSkill: [
      { skill: 'mining', lv: '1' },
      { skill: 'transporting', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/fuddler.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Killamari',
    number: '23',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'transporting', lv: '2' },
      { skill: 'gathering', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/killamari.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Mau',
    number: '24',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'farming', lv: '1' }],
    searchFilter: [''],
    image: '/pal/icon/mau.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Mau Cryst',
    number: '24B',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'cooling', lv: '1' },
      { skill: 'farming', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/mauCryst.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Celaray',
    number: '25',
    caught: '0',
    element: ['water'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'watering', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/celaray.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Direhowl',
    number: '26',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'gathering', lv: '1' }],
    searchFilter: [''],
    image: '/pal/icon/direhowl.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Tocotoco',
    number: '27',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'gathering', lv: '1' }],
    searchFilter: [''],
    image: '/pal/icon/tocotoco.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
  {
    id: crypto.randomUUID(),
    name: '',
    number: '',
    caught: '0',
    element: [''],
    workSkill: [
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
      { skill: '', lv: '1' },
    ],
    searchFilter: [''],
    image: '/pal/icon/.webp',
  },
]

export const elements = [
  { name: 'dark', value: 'dark', image: '/icon/element/dark.webp' },
  { name: 'dragon', value: 'dragon', image: '/icon/element/dragon.webp' },
  { name: 'electric', value: 'electric', image: '/icon/element/electric.webp' },
  { name: 'fire', value: 'fire', image: '/icon/element/fire.webp' },
  { name: 'grass', value: 'grass', image: '/icon/element/grass.webp' },
  { name: 'ground', value: 'ground', image: '/icon/element/ground.webp' },
  { name: 'ice', value: 'ice', image: '/icon/element/ice.webp' },
  { name: 'neutral', value: 'neutral', image: '/icon/element/neutral.webp' },
  { name: 'water', value: 'water', image: '/icon/element/water.webp' },
]

export const workSuitability = [
  { name: 'cooling', value: 'cooling', srcImage: '/icon/work/cooling.webp' },
  { name: 'farming', value: 'farming', srcImage: '/icon/work/farming.webp' },
  {
    name: 'gathering',
    value: 'gathering',
    srcImage: '/icon/work/gathering.webp',
  },
  {
    name: 'generate electricity',
    value: 'generateElectricity',
    srcImage: '/icon/work/generateElectricity.webp',
  },
  {
    name: 'handiwork',
    value: 'handiwork',
    srcImage: '/icon/work/handiwork.webp',
  },
  { name: 'kindling', value: 'kindling', srcImage: '/icon/work/kindling.webp' },
  {
    name: 'lumbering',
    value: 'lumbering',
    srcImage: '/icon/work/lumbering.webp',
  },
  {
    name: 'medicine production',
    value: 'medicineProduction',
    srcImage: '/icon/work/medicineProduction.webp',
  },
  { name: 'mining', value: 'mining', srcImage: '/icon/work/mining.webp' },
  { name: 'planting', value: 'planting', srcImage: '/icon/work/planting.webp' },
  {
    name: 'transporting',
    value: 'transporting',
    srcImage: '/icon/work/transporting.webp',
  },
  { name: 'watering', value: 'watering', srcImage: '/icon/work/watering.webp' },
]
