type palsType = {
  id: string
  name: string
  number: string
  caught: string
  element: (
    | 'dark'
    | 'dragon'
    | 'electric'
    | 'fire'
    | 'grass'
    | 'ground'
    | 'ice'
    | 'neutral'
    | 'water'
  )[]
  workSkill: {
    skill:
      | 'cooling'
      | 'farming'
      | 'gathering'
      | 'generatingElectricity'
      | 'handiwork'
      | 'kindling'
      | 'lumbering'
      | 'medicineProduction'
      | 'mining'
      | 'planting'
      | 'transporting'
      | 'watering'
    lv: '1' | '2' | '3' | '4'
  }[]
  searchFilter: string
  image: string
}[]

export const pals: palsType = [
  {
    id: crypto.randomUUID(),
    name: 'Lamball',
    number: '1',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'farming', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: 'Lamball',
    image: '/pal/icon/lamball.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Cattiva',
    number: '2',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'mining', lv: '1' },
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/cattiva.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Chikipi',
    number: '3',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'farming', lv: '1' },
      { skill: 'gathering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/chikipi.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Lifmunk',
    number: '4',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'lumbering', lv: '1' },
      { skill: 'medicineProduction', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/lifmunk.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Foxparks',
    number: '5',
    caught: '0',
    element: ['fire'],
    workSkill: [{ skill: 'kindling', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/foxparks.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Fuack',
    number: '6',
    caught: '0',
    element: ['water'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'watering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/fuack.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Sparkit',
    number: '7',
    caught: '0',
    element: ['electric'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'generatingElectricity', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/sparkit.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Tanzee',
    number: '8',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '1' },
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'lumbering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/tanzee.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Rooby',
    number: '9',
    caught: '0',
    element: ['fire'],
    workSkill: [{ skill: 'kindling', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/rooby.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Pengullet',
    number: '10',
    caught: '0',
    element: ['water', 'ice'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'watering', lv: '1' },
      { skill: 'cooling', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/pengullet.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Penking',
    number: '11',
    caught: '0',
    element: ['water', 'ice'],
    workSkill: [
      { skill: 'mining', lv: '2' },
      { skill: 'transporting', lv: '2' },
      { skill: 'watering', lv: '2' },
      { skill: 'cooling', lv: '2' },
      { skill: 'handiwork', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/penking.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jolthog',
    number: '12',
    caught: '0',
    element: ['electric'],
    workSkill: [{ skill: 'generatingElectricity', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/jolthog.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jolthog Cryst',
    number: '12B',
    caught: '0',
    element: ['ice'],
    workSkill: [{ skill: 'cooling', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/jolthogCryst.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Gumoss',
    number: '13',
    caught: '0',
    element: ['grass', 'ground'],
    workSkill: [{ skill: 'planting', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/gumoss.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Vixy',
    number: '14',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'farming', lv: '1' },
      { skill: 'gathering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/vixy.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Hoocrates',
    number: '15',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'gathering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/hoocrates.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Teafant',
    number: '16',
    caught: '0',
    element: ['water'],
    workSkill: [{ skill: 'watering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/teafant.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Depresso',
    number: '17',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'mining', lv: '1' },
      { skill: 'transporting', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/depresso.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Cremis',
    number: '18',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'farming', lv: '1' },
      { skill: 'gathering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/cremis.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Daedream',
    number: '19',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/daedream.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Rushoar',
    number: '20',
    caught: '0',
    element: ['ground'],
    workSkill: [{ skill: 'mining', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/rushoar.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Nox',
    number: '21',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'gathering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/nox.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Fuddler',
    number: '22',
    caught: '0',
    element: ['ground'],
    workSkill: [
      { skill: 'mining', lv: '1' },
      { skill: 'transporting', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/fuddler.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Killamari',
    number: '23',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'transporting', lv: '2' },
      { skill: 'gathering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/killamari.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Mau',
    number: '24',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'farming', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/mau.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Mau Cryst',
    number: '24B',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'cooling', lv: '1' },
      { skill: 'farming', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/mauCryst.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Celaray',
    number: '25',
    caught: '0',
    element: ['water'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'watering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/celaray.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Direhowl',
    number: '26',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'gathering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/direhowl.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Tocotoco',
    number: '27',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'gathering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/tocotoco.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Flopie',
    number: '28',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '1' },
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'medicineProduction', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/flopie.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Mozzarina',
    number: '29',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'farming', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/mozzarina.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Bristla',
    number: '30',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '1' },
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'medicineProduction', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/bristla.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Gobfin',
    number: '31',
    caught: '0',
    element: ['water'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'watering', lv: '2' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/gobfin.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Gobfin Ignis',
    number: '31B',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'kindling', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/gobfinIgnis.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Hangyu',
    number: '32',
    caught: '0',
    element: ['ground'],
    workSkill: [
      { skill: 'transporting', lv: '2' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/hangyu.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Hangyu Cryst',
    number: '32B',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'transporting', lv: '2' },
      { skill: 'cooling', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/hangyuCryst.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Mossanda',
    number: '33',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '2' },
      { skill: 'transporting', lv: '3' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/mossanda.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Mossanda Lux',
    number: '33B',
    caught: '0',
    element: ['electric'],
    workSkill: [
      { skill: 'transporting', lv: '3' },
      { skill: 'generatingElectricity', lv: '2' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/mossandaLux.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Woolipop',
    number: '34',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'farming', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/woolipop.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Caprity',
    number: '35',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '2' },
      { skill: 'farming', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/caprity.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Melpaca',
    number: '36',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'farming', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/melpaca.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Eikthyrdeer',
    number: '37',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'lumbering', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/eikthyrdeer.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Eikthyrdeer Terra',
    number: '37B',
    caught: '0',
    element: ['ground'],
    workSkill: [{ skill: 'lumbering', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/eikthyrdeerTerra.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Nitewing',
    number: '38',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'gathering', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/nitewing.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Ribbuny',
    number: '39',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/ribbuny.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Incineram',
    number: '40',
    caught: '0',
    element: ['fire', 'dark'],
    workSkill: [
      { skill: 'mining', lv: '1' },
      { skill: 'transporting', lv: '2' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'kindling', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/incineram.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Incineram Noct',
    number: '40B',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'mining', lv: '1' },
      { skill: 'transporting', lv: '2' },
      { skill: 'handiwork', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/incineramNoct.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Cinnamoth',
    number: '41',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '2' },
      { skill: 'medicineProduction', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/cinnamoth.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Arsox',
    number: '42',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'kindling', lv: '2' },
      { skill: 'lumbering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/arsox.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Dumud',
    number: '43',
    caught: '0',
    element: ['ground'],
    workSkill: [
      { skill: 'mining', lv: '2' },
      { skill: 'transporting', lv: '1' },
      { skill: 'watering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/dumud.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Cawgnito',
    number: '44',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'lumbering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/cawgnito.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Leezpunk',
    number: '45',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/leezpunk.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Leezpunk Ignis',
    number: '45B',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'kindling', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/leezpunkIgnis.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Loupmoon',
    number: '46',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'handiwork', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/loupmoon.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Galeclaw',
    number: '47',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'gathering', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/galeclaw.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Robinquill',
    number: '48',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '1' },
      { skill: 'transporting', lv: '2' },
      { skill: 'gathering', lv: '2' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'lumbering', lv: '1' },
      { skill: 'medicineProduction', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/robinquill.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Robinquill Terra',
    number: '48B',
    caught: '0',
    element: ['grass', 'ground'],
    workSkill: [
      { skill: 'transporting', lv: '2' },
      { skill: 'gathering', lv: '2' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'lumbering', lv: '1' },
      { skill: 'medicineProduction', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/robinquillTerra.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Gorirat',
    number: '49',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'transporting', lv: '3' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/gorirat.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Beegarde',
    number: '50',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '1' },
      { skill: 'transporting', lv: '2' },
      { skill: 'farming', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'lumbering', lv: '1' },
      { skill: 'medicineProduction', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/beegarde.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Elizabee',
    number: '51',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '2' },
      { skill: 'gathering', lv: '2' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'lumbering', lv: '1' },
      { skill: 'medicineProduction', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/elizabee.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Grintale',
    number: '52',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'gathering', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/grintale.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Swee',
    number: '53',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'cooling', lv: '1' },
      { skill: 'gathering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/swee.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Sweepa',
    number: '54',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'cooling', lv: '2' },
      { skill: 'gathering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/sweepa.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Chillet',
    number: '55',
    caught: '0',
    element: ['ice', 'dragon'],
    workSkill: [
      { skill: 'cooling', lv: '1' },
      { skill: 'gathering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/chillet.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Univolt',
    number: '56',
    caught: '0',
    element: ['electric'],
    workSkill: [
      { skill: 'generatingElectricity', lv: '2' },
      { skill: 'lumbering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/univolt.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Foxcicle',
    number: '57',
    caught: '0',
    element: ['ice'],
    workSkill: [{ skill: 'cooling', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/foxcicle.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Pyrin',
    number: '58',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'kindling', lv: '2' },
      { skill: 'lumbering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/pyrin.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Pyrin Noct',
    number: '58B',
    caught: '0',
    element: ['fire', 'dark'],
    workSkill: [
      { skill: 'kindling', lv: '2' },
      { skill: 'lumbering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/pyrinNoct.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Reindrix',
    number: '59',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'cooling', lv: '2' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/reindrix.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Rayhound',
    number: '60',
    caught: '0',
    element: ['electric'],
    workSkill: [{ skill: 'generatingElectricity', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/rayhound.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Kitsun',
    number: '61',
    caught: '0',
    element: ['fire'],
    workSkill: [{ skill: 'kindling', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/kitsun.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Dazzi',
    number: '62',
    caught: '0',
    element: ['electric'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'generatingElectricity', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/dazzi.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Lunaris',
    number: '63',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/lunaris.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Dinossom',
    number: '',
    caught: '0',
    element: ['grass', 'dragon'],
    workSkill: [
      { skill: 'planting', lv: '2' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/Dinossom.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Dinossom Lux',
    number: '64B',
    caught: '0',
    element: ['electric', 'dragon'],
    workSkill: [
      { skill: 'generatingElectricity', lv: '2' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/dinossomLux.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Surfent',
    number: '65',
    caught: '0',
    element: ['water'],
    workSkill: [{ skill: 'watering', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/surfent.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Surfent Terra',
    number: '65B',
    caught: '0',
    element: ['ground'],
    workSkill: [{ skill: 'gathering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/surfentTerra.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Maraith',
    number: '66',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'mining', lv: '1' },
      { skill: 'gathering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/maraith.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Digtoise',
    number: '67',
    caught: '0',
    element: ['ground'],
    workSkill: [{ skill: 'mining', lv: '3' }],
    searchFilter: '',
    image: '/pal/icon/digtoise.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Tombat',
    number: '68',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'mining', lv: '2' },
      { skill: 'transporting', lv: '2' },
      { skill: 'gathering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/tombat.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Lovander',
    number: '69',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'mining', lv: '1' },
      { skill: 'transporting', lv: '2' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'medicineProduction', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/lovander.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Flambelle',
    number: '70',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'farming', lv: '1' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'kindling', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/flambelle.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Vanwyrm',
    number: '71',
    caught: '0',
    element: ['fire', 'dark'],
    workSkill: [
      { skill: 'transporting', lv: '3' },
      { skill: 'kindling', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/vanwyrm.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Vanwyrm Cryst',
    number: '71B',
    caught: '0',
    element: ['ice', 'dark'],
    workSkill: [
      { skill: 'transporting', lv: '3' },
      { skill: 'cooling', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/vanwyrmCryst.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Bushi',
    number: '72',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'transporting', lv: '2' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'kindling', lv: '2' },
      { skill: 'lumbering', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/bushi.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Beakon',
    number: '73',
    caught: '0',
    element: ['electric'],
    workSkill: [
      { skill: 'transporting', lv: '3' },
      { skill: 'gathering', lv: '1' },
      { skill: 'generatingElectricity', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/beakon.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Ragnahawk',
    number: '74',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'transporting', lv: '3' },
      { skill: 'kindling', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/ragnahawk.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Katress',
    number: '75',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'transporting', lv: '2' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'medicineProduction', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/katress.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Wixen',
    number: '76',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'transporting', lv: '2' },
      { skill: 'handiwork', lv: '3' },
      { skill: 'kindling', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/wixen.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Verdash',
    number: '77',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '2' },
      { skill: 'transporting', lv: '2' },
      { skill: 'gathering', lv: '3' },
      { skill: 'handiwork', lv: '3' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/verdash.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Vaelet',
    number: '78',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '2' },
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '2' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'medicineProduction', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/vaelet.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Sibelyx',
    number: '79',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'cooling', lv: '2' },
      { skill: 'farming', lv: '1' },
      { skill: 'medicineProduction', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/sibelyx.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Elphidran',
    number: '80',
    caught: '0',
    element: ['dragon'],
    workSkill: [{ skill: 'lumbering', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/elphidran.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Elphidran Aqua',
    number: '80B',
    caught: '0',
    element: ['dragon', 'water'],
    workSkill: [
      { skill: 'watering', lv: '3' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/elphidranAqua.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Kelpsea',
    number: '81',
    caught: '0',
    element: ['water'],
    workSkill: [{ skill: 'watering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/kelpsea.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Kelpsea Ignis',
    number: '81B',
    caught: '0',
    element: ['fire'],
    workSkill: [{ skill: 'kindling', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/kelpseaIgnis.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Azurobe',
    number: '82',
    caught: '0',
    element: ['water', 'dragon'],
    workSkill: [{ skill: 'watering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/azurobe.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Cryolinx',
    number: '83',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'cooling', lv: '3' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/cryolinx.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Blazehowl',
    number: '84',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'kindling', lv: '3' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/blazehowl.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Blazehowl Noct',
    number: '84B',
    caught: '0',
    element: ['fire', 'dark'],
    workSkill: [
      { skill: 'kindling', lv: '3' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/blazehowlNoct.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Relaxaurus',
    number: '85',
    caught: '0',
    element: ['dragon', 'water'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'watering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/relaxaurus.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Relaxaurus Lux',
    number: '85B',
    caught: '0',
    element: ['dragon', 'electric'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'generatingElectricity', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/relaxaurusLux.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Broncherry',
    number: '',
    caught: '0',
    element: ['grass'],
    workSkill: [{ skill: 'planting', lv: '3' }],
    searchFilter: '',
    image: '/pal/icon/broncherry.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Broncherry Aqua',
    number: '86B',
    caught: '0',
    element: ['grass', 'water'],
    workSkill: [{ skill: 'watering', lv: '3' }],
    searchFilter: '',
    image: '/pal/icon/broncherryAqua.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Petallia',
    number: '87',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '3' },
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '2' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'medicineProduction', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/petallia.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Reptyro',
    number: '88',
    caught: '0',
    element: ['fire', 'ground'],
    workSkill: [
      { skill: 'mining', lv: '3' },
      { skill: 'kindling', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/reptyro.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Ice Reptyro',
    number: '88B',
    caught: '0',
    element: ['ice', 'ground'],
    workSkill: [
      { skill: 'mining', lv: '3' },
      { skill: 'cooling', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/iceReptyro.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Kingpaca',
    number: '89',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'gathering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/kingpaca.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Ice Kingpaca',
    number: '89B',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'cooling', lv: '3' },
      { skill: 'gathering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/iceKingpaca.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Mammorest',
    number: '90',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'mining', lv: '2' },
      { skill: 'planting', lv: '2' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/mammorest.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Mammorest Cryst',
    number: '90B',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'mining', lv: '2' },
      { skill: 'cooling', lv: '2' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/mammorestCryst.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Wumpo',
    number: '91',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'transporting', lv: '4' },
      { skill: 'cooling', lv: '2' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'lumbering', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/wumpo.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Wumpo Botan',
    number: '91B',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '1' },
      { skill: 'transporting', lv: '4' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'lumbering', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/wumpoBotan.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Warsect',
    number: '92',
    caught: '0',
    element: ['ground', 'grass'],
    workSkill: [
      { skill: 'planting', lv: '1' },
      { skill: 'transporting', lv: '3' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'lumbering', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/warsect.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Fenglope',
    number: '93',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'lumbering', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/fenglope.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Felbat',
    number: '94',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'medicineProduction', lv: '3' }],
    searchFilter: '',
    image: '/pal/icon/felbat.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Quivern',
    number: '95',
    caught: '0',
    element: ['dragon'],
    workSkill: [
      { skill: 'mining', lv: '2' },
      { skill: 'transporting', lv: '3' },
      { skill: 'gathering', lv: '2' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/quivern.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Blazamut',
    number: '96',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'mining', lv: '4' },
      { skill: 'kindling', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/blazamut.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Helzephyr',
    number: '97',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'transporting', lv: '3' }],
    searchFilter: '',
    image: '/pal/icon/helzephyr.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Astegon',
    number: '98',
    caught: '0',
    element: ['dragon', 'dark'],
    workSkill: [
      { skill: 'mining', lv: '4' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/astegon.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Menasting',
    number: '99',
    caught: '0',
    element: ['dark', 'ground'],
    workSkill: [
      { skill: 'mining', lv: '3' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/menasting.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Anubis',
    number: '100',
    caught: '0',
    element: ['ground'],
    workSkill: [
      { skill: 'mining', lv: '3' },
      { skill: 'transporting', lv: '2' },
      { skill: 'handiwork', lv: '4' },
    ],
    searchFilter: '',
    image: '/pal/icon/anubis.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jormuntide',
    number: '101',
    caught: '0',
    element: ['dragon', 'water'],
    workSkill: [{ skill: 'watering', lv: '4' }],
    searchFilter: '',
    image: '/pal/icon/jormuntide.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jormuntide Ignis',
    number: '101B',
    caught: '0',
    element: ['dragon', 'fire'],
    workSkill: [{ skill: 'kindling', lv: '4' }],
    searchFilter: '',
    image: '/pal/icon/jormuntideIgnis.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Suzaku',
    number: '102',
    caught: '0',
    element: ['fire'],
    workSkill: [{ skill: 'kindling', lv: '3' }],
    searchFilter: '',
    image: '/pal/icon/suzaku.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Suzaku Aqua',
    number: '102B',
    caught: '0',
    element: ['water'],
    workSkill: [{ skill: 'watering', lv: '3' }],
    searchFilter: '',
    image: '/pal/icon/suzakuAqua.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Grizzbolt',
    number: '103',
    caught: '0',
    element: ['electric'],
    workSkill: [
      { skill: 'transporting', lv: '3' },
      { skill: 'generatingElectricity', lv: '3' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/grizzbolt.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Lyleen',
    number: '104',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '4' },
      { skill: 'gathering', lv: '2' },
      { skill: 'handiwork', lv: '3' },
      { skill: 'medicineProduction', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/lyleen.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Lyleen Noct',
    number: '104B',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'gathering', lv: '2' },
      { skill: 'handiwork', lv: '3' },
      { skill: 'medicineProduction', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/lyleenNoct.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Faleris',
    number: '105',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'transporting', lv: '3' },
      { skill: 'kindling', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/faleris.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Orserk',
    number: '106',
    caught: '0',
    element: ['dragon', 'electric'],
    workSkill: [
      { skill: 'transporting', lv: '3' },
      { skill: 'generatingElectricity', lv: '4' },
      { skill: 'handiwork', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/orserk.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Shadowbeak',
    number: '107',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'gathering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/shadowbeak.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Paladius',
    number: '108',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'mining', lv: '2' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/paladius.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Necromus',
    number: '109',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'mining', lv: '2' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/necromus.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Frostallion',
    number: '110',
    caught: '0',
    element: ['ice'],
    workSkill: [{ skill: 'cooling', lv: '4' }],
    searchFilter: '',
    image: '/pal/icon/frostallion.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Frostallion Noct',
    number: '110B',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'gathering', lv: '4' }],
    searchFilter: '',
    image: '/pal/icon/frostallionNoct.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jetragon',
    number: '111',
    caught: '0',
    element: ['dragon'],
    workSkill: [{ skill: 'gathering', lv: '3' }],
    searchFilter: '',
    image: '/pal/icon/Jetragon.webp',
  },
]

type palsBreadingType = {
  pal: string
  parents: string[][]
}[]

export const palsBreading: palsBreadingType = [
  {
    pal: 'Lamball',
    parents: [
      ['Lamball', 'Lamball'],
      ['Lamball', 'Cattiva'],
      ['Cattiva', 'Mau'],
      ['Chikipi', 'Lifmunk'],
      ['Chikipi', 'Mau Cryst'],
      ['Vixy', 'Teafant'],
      ['Vixy', 'Mau'],
      ['Teafant', 'Cremis'],
      ['Teafant', 'Mau Cryst'],
      ['Cremis', 'Mau'],
    ],
  },
  {
    pal: 'Cattiva',
    parents: [
      ['Lamball', 'Vixy'],
      ['Lamball', 'Cremis'],
      ['Cattiva', 'Cattiva'],
      ['Cattiva', 'Cremis'],
      ['Chikipi', 'Hangyu'],
      ['Chikipi', 'Hangyu Cryst'],
      ['Lifmunk', 'Teafant'],
      ['Mau', 'Mau Cryst'],
    ],
  },
  { pal: 'Chikipi', parents: [['Chikipi', 'Chikipi']] },
  {
    pal: 'Lifmunk',
    parents: [
      ['Lamball', 'Foxparks'],
      ['Lamball', 'Sparkit'],
      ['Lamball', 'Hoocrates'],
      ['Lamball', 'Depresso'],
      ['Lamball', 'Flambelle'],
      ['Cattiva', 'Foxparks'],
      ['Cattiva', 'Sparkit'],
      ['Cattiva', 'Hoocrates'],
      ['Cattiva', 'Hangyu'],
      ['Cattiva', 'Flambelle'],
      ['Chikipi', 'Pengullet'],
      ['Chikipi', 'Jolthog'],
      ['Chikipi', 'Jolthog Cryst'],
      ['Chikipi', 'Depresso'],
      ['Lifmunk', 'Lifmunk'],
      ['Lifmunk', 'Vixy'],
      ['Lifmunk', 'Mau Cryst'],
      ['Lifmunk', 'Hangyu'],
      ['Lifmunk', 'Hangyu Cryst'],
      ['Foxparks', 'Vixy'],
      ['Foxparks', 'Cremis'],
      ['Foxparks', 'Mau'],
      ['Sparkit', 'Vixy'],
      ['Sparkit', 'Cremis'],
      ['Sparkit', 'Mau Cryst'],
      ['Jolthog', 'Teafant'],
      ['Jolthog', 'Mau'],
      ['Jolthog Cryst', 'Teafant'],
      ['Vixy', 'Hangyu'],
      ['Vixy', 'Hangyu Cryst'],
      ['Vixy', 'Flambelle'],
      ['Hoocrates', 'Teafant'],
      ['Hoocrates', 'Mau'],
      ['Teafant', 'Depresso'],
      ['Depresso', 'Mau'],
      ['Cremis', 'Hangyu'],
      ['Cremis', 'Hangyu Cryst'],
      ['Cremis', 'Flambelle'],
      ['Mau Cryst', 'Hangyu'],
      ['Mau Cryst', 'Hangyu Cryst'],
    ],
  },
  {
    pal: 'Foxparks',
    parents: [
      ['Lamball', 'Fuack'],
      ['Lamball', 'Bristla'],
      ['Cattiva', 'Fuack'],
      ['Cattiva', 'Tocotoco'],
      ['Chikipi', 'Killamari'],
      ['Chikipi', 'Swee'],
      ['Lifmunk', 'Jolthog'],
      ['Lifmunk', 'Jolthog Cryst'],
      ['Foxparks', 'Foxparks'],
      ['Foxparks', 'Hoocrates'],
      ['Sparkit', 'Hoocrates'],
      ['Sparkit', 'Depresso'],
      ['Pengullet', 'Vixy'],
      ['Pengullet', 'Mau Cryst'],
      ['Jolthog', 'Hangyu'],
      ['Jolthog', 'Hangyu Cryst'],
      ['Jolthog Cryst', 'Mau Cryst'],
      ['Vixy', 'Tocotoco'],
      ['Hoocrates', 'Flambelle'],
      ['Teafant', 'Ribunny'],
      ['Teafant', 'Swee'],
      ['Depresso', 'Hangyu'],
      ['Depresso', 'Hangyu Cryst'],
      ['Cremis', 'Tocotoco'],
      ['Mau', 'Bristla'],
      ['Mau', 'Ribunny'],
    ],
  },
  {
    pal: 'Fuack',
    parents: [
      ['Lamball', 'Woolipop'],
      ['Chikipi', 'Rooby'],
      ['Chikipi', 'Wixen'],
      ['Lifmunk', 'Daedream'],
      ['Foxparks', 'Kelpsea'],
      ['Fuack', 'Fuack'],
      ['Sparkit', 'Tanzee'],
      ['Tanzee', 'Flambelle'],
      ['Pengullet', 'Ribunny'],
      ['Jolthog', 'Killamari'],
      ['Jolthog Cryst', 'Swee'],
      ['Gumoss', 'Hangyu'],
      ['Gumoss', 'Hangyu Cryst'],
      ['Gumoss (Special)', 'Hangyu'],
      ['Gumoss (Special)', 'Hangyu Cryst'],
      ['Vixy', 'Dazzi'],
      ['Hoocrates', 'Kelpsea Ignis'],
      ['Depresso', 'Flopie'],
      ['Cremis', 'Dazzi'],
      ['Daedream', 'Hangyu Cryst'],
      ['Nox', 'Mau'],
      ['Fuddler', 'Mau Cryst'],
      ['Tocotoco', 'Bristla'],
      ['Flambelle', 'Kelpsea'],
    ],
  },
  {
    pal: 'Sparkit',
    parents: [
      ['Lamball', 'Pengullet'],
      ['Cattiva', 'Jolthog Cryst'],
      ['Chikipi', 'Bristla'],
      ['Lifmunk', 'Hoocrates'],
      ['Foxparks', 'Hangyu'],
      ['Foxparks', 'Hangyu Cryst'],
      ['Fuack', 'Teafant'],
      ['Sparkit', 'Sparkit'],
      ['Sparkit', 'Flambelle'],
      ['Jolthog', 'Vixy'],
      ['Jolthog', 'Cremis'],
      ['Jolthog Cryst', 'Cremis'],
      ['Depresso', 'Mau Cryst'],
      ['Mau', 'Tocotoco'],
      ['Hangyu', 'Flambelle'],
      ['Hangyu Cryst', 'Flambelle'],
    ],
  },
  {
    pal: 'Tanzee',
    parents: [
      ['Lamball', 'Galeclaw'],
      ['Lamball', 'Robinquill'],
      ['Cattiva', 'Galeclaw'],
      ['Cattiva', 'Gorirat'],
      ['Chikipi', 'Robinquill Terra'],
      ['Chikipi', 'Verdash'],
      ['Lifmunk', 'Direhowl'],
      ['Lifmunk', 'Beegarde'],
      ['Foxparks', 'Gobfin'],
      ['Foxparks', 'Gobfin Ignis'],
      ['Fuack', 'Wixen'],
      ['Sparkit', 'Gobfin'],
      ['Sparkit', 'Cawgnito'],
      ['Tanzee', 'Tanzee'],
      ['Tanzee', 'Gumoss'],
      ['Tanzee', 'Gumoss (Special)'],
      ['Rooby', 'Pengullet'],
      ['Rooby', 'Tocotoco'],
      ['Pengullet', 'Leezpunk Ignis'],
      ['Pengullet', 'Maraith'],
      ['Jolthog', 'Rushoar'],
      ['Jolthog', 'Leezpunk'],
      ['Jolthog Cryst', 'Rushoar'],
      ['Jolthog Cryst', 'Leezpunk Ignis'],
      ['Gumoss', 'Kelpsea'],
      ['Gumoss (Special)', 'Kelpsea'],
      ['Vixy', 'Gorirat'],
      ['Vixy', 'Vaelet'],
      ['Hoocrates', 'Gobfin Ignis'],
      ['Hoocrates', 'Lunaris'],
      ['Teafant', 'Robinquill Terra'],
      ['Teafant', 'Felbat'],
      ['Depresso', 'Leezpunk'],
      ['Depresso', 'Lunaris'],
      ['Cremis', 'Gorirat'],
      ['Cremis', 'Vaelet'],
      ['Daedream', 'Kelpsea'],
      ['Daedream', 'Kelpsea Ignis'],
      ['Nox', 'Bristla'],
      ['Nox', 'Ribunny'],
      ['Fuddler', 'Flopie'],
      ['Fuddler', 'Kelpsea Ignis'],
      ['Killamari', 'Dazzi'],
      ['Mau', 'Robinquill'],
      ['Mau', 'Felbat'],
      ['Mau Cryst', 'Direhowl'],
      ['Mau Cryst', 'Vaelet'],
      ['Tocotoco', 'Maraith'],
      ['Tocotoco', 'Wixen'],
      ['Flopie', 'Dazzi'],
      ['Gobfin', 'Flambelle'],
      ['Gobfin Ignis', 'Flambelle'],
      ['Hangyu', 'Cawgnito'],
      ['Hangyu', 'Beegarde'],
      ['Hangyu Cryst', 'Cawgnito'],
      ['Hangyu Cryst', 'Beegarde'],
      ['Woolipop', 'Ribunny'],
      ['Woolipop', 'Swee'],
    ],
  },
  {
    pal: 'Rooby',
    parents: [
      ['Lamball', 'Broncherry Aqua'],
      ['Cattiva', 'Digtoise'],
      ['Chikipi', 'Dinossom Lux'],
      ['Lifmunk', 'Reindrix'],
      ['Foxparks', 'Mozzarina'],
      ['Fuack', 'Fenglope'],
      ['Sparkit', 'Eikthyrdeer Terra'],
      ['Sparkit', 'Dumud'],
      ['Tanzee', 'Direhowl'],
      ['Rooby', 'Rooby'],
      ['Rooby', 'Maraith'],
      ['Jolthog', 'Lovander'],
      ['Jolthog Cryst', 'Loupmoon'],
      ['Gumoss', 'Beegarde'],
      ['Gumoss (Special)', 'Beegarde'],
      ['Vixy', 'Broncherry'],
      ['Hoocrates', 'Eikthyrdeer'],
      ['Teafant', 'Dinossom'],
      ['Depresso', 'Caprity'],
      ['Cremis', 'Digtoise'],
      ['Daedream', 'Cawgnito'],
      ['Rushoar', 'Nox'],
      ['Fuddler', 'Gobfin'],
      ['Killamari', 'Robinquill'],
      ['Mau', 'Kitsun'],
      ['Mau Cryst', 'Celaray'],
      ['Flopie', 'Galeclaw'],
      ['Bristla', 'Verdash'],
      ['Gobfin Ignis', 'Dazzi'],
      ['Hangyu', 'Melpaca'],
      ['Hangyu Cryst', 'Melpaca'],
      ['Woolipop', 'Leezpunk'],
      ['Eikthyrdeer Terra', 'Flambelle'],
      ['Ribunny', 'Robinquill Terra'],
      ['Gorirat', 'Kelpsea Ignis'],
      ['Swee', 'Felbat'],
      ['Maraith', 'Wixen'],
      ['Vaelet', 'Kelpsea'],
    ],
  },
  {
    pal: 'Pengullet',
    parents: [
      ['Lamball', 'Gumoss'],
      ['Lamball', 'Gumoss (Special)'],
      ['Lamball', 'Daedream'],
      ['Cattiva', 'Tanzee'],
      ['Cattiva', 'Gumoss'],
      ['Cattiva', 'Gumoss (Special)'],
      ['Chikipi', 'Dazzi'],
      ['Lifmunk', 'Flopie'],
      ['Lifmunk', 'Kelpsea Ignis'],
      ['Foxparks', 'Ribunny'],
      ['Foxparks', 'Swee'],
      ['Fuack', 'Jolthog'],
      ['Fuack', 'Depresso'],
      ['Sparkit', 'Killamari'],
      ['Sparkit', 'Swee'],
      ['Tanzee', 'Vixy'],
      ['Tanzee', 'Cremis'],
      ['Pengullet', 'Pengullet'],
      ['Pengullet', 'Jolthog Cryst'],
      ['Jolthog', 'Tocotoco'],
      ['Jolthog Cryst', 'Tocotoco'],
      ['Gumoss', 'Cremis'],
      ['Gumoss (Special)', 'Cremis'],
      ['Vixy', 'Kelpsea'],
      ['Hoocrates', 'Bristla'],
      ['Hoocrates', 'Ribunny'],
      ['Teafant', 'Fuddler'],
      ['Teafant', 'Dazzi'],
      ['Depresso', 'Bristla'],
      ['Cremis', 'Kelpsea'],
      ['Daedream', 'Mau'],
      ['Fuddler', 'Mau'],
      ['Killamari', 'Hangyu'],
      ['Killamari', 'Hangyu Cryst'],
      ['Killamari', 'Flambelle'],
      ['Mau Cryst', 'Kelpsea'],
      ['Mau Cryst', 'Kelpsea Ignis'],
      ['Flopie', 'Hangyu'],
      ['Flopie', 'Hangyu Cryst'],
      ['Hangyu Cryst', 'Kelpsea Ignis'],
      ['Ribunny', 'Flambelle'],
      ['Swee', 'Flambelle'],
    ],
  },
  {
    pal: 'Penking',
    parents: [
      ['Penking', 'Penking'],
      ['Penking', 'Grintale'],
      ['Penking', 'Elphidran Aqua'],
      ['Mozzarina', 'Cryolinx'],
      ['Mozzarina', 'Orserk'],
      ['Mozzarina', 'Frostallion'],
      ['Mossanda', 'Vanwyrm Cryst'],
      ['Mossanda Lux', 'Vanwyrm'],
      ['Mossanda Lux', 'Bushi'],
      ['Caprity', 'Frostallion'],
      ['Caprity', 'Frostallion Noct'],
      ['Melpaca', 'Astegon'],
      ['Melpaca', 'Orserk'],
      ['Eikthyrdeer', 'Cryolinx'],
      ['Eikthyrdeer', 'Frostallion'],
      ['Eikthyrdeer Terra', 'Cryolinx'],
      ['Eikthyrdeer Terra', 'Astegon'],
      ['Eikthyrdeer Terra', 'Orserk'],
      ['Nitewing', 'Vanwyrm Cryst'],
      ['Incineram', 'Sibelyx'],
      ['Incineram', 'Ice Kingpaca'],
      ['Incineram', 'Wumpo'],
      ['Incineram Noct', 'Sibelyx'],
      ['Incineram Noct', 'Kingpaca'],
      ['Incineram Noct', 'Wumpo'],
      ['Cinnamoth', 'Surfent'],
      ['Cinnamoth', 'Surfent Terra'],
      ['Cinnamoth', 'Elphidran'],
      ['Arsox', 'Pyrin Noct'],
      ['Arsox', 'Menasting'],
      ['Arsox', 'Lyleen'],
      ['Dumud', 'Astegon'],
      ['Dumud', 'Orserk'],
      ['Loupmoon', 'Paladius'],
      ['Loupmoon', 'Frostallion Noct'],
      ['Loupmoon', 'Jetragon'],
      ['Galeclaw', 'Blazamut'],
      ['Robinquill', 'Blazamut'],
      ['Robinquill', 'Suzaku Aqua'],
      ['Robinquill Terra', 'Suzaku'],
      ['Robinquill Terra', 'Suzaku Aqua'],
      ['Gorirat', 'Blazamut'],
      ['Elizabee', 'Katress'],
      ['Elizabee', 'Blazehowl'],
      ['Grintale', 'Elphidran'],
      ['Grintale', 'Elphidran Aqua'],
      ['Sweepa', 'Vanwyrm Cryst'],
      ['Sweepa', 'Bushi'],
      ['Chillet', 'Pyrin Noct'],
      ['Chillet', 'Ice Reptyro'],
      ['Chillet', 'Lyleen'],
      ['Univolt', 'Pyrin'],
      ['Univolt', 'Quivern'],
      ['Univolt', 'Faleris'],
      ['Foxcicle', 'Relaxaurus'],
      ['Foxcicle', 'Relaxaurus Lux'],
      ['Foxcicle', 'Mammorest Cryst'],
      ['Pyrin', 'Blazehowl Noct'],
      ['Pyrin Noct', 'Dinossom Lux'],
      ['Reindrix', 'Astegon'],
      ['Rayhound', 'Mammorest'],
      ['Rayhound', 'Mammorest Cryst'],
      ['Rayhound', 'Jormuntide'],
      ['Rayhound', 'Jormuntide Ignis'],
      ['Kitsun', 'Beakon'],
      ['Kitsun', 'Grizzbolt'],
      ['Kitsun', 'Lyleen Noct'],
      ['Dinossom', 'Beakon'],
      ['Dinossom', 'Ice Reptyro'],
      ['Dinossom', 'Lyleen Noct'],
      ['Dinossom Lux', 'Beakon'],
      ['Dinossom Lux', 'Ice Reptyro'],
      ['Surfent', 'Kingpaca'],
      ['Surfent', 'Wumpo Botan'],
      ['Surfent Terra', 'Azurobe'],
      ['Surfent Terra', 'Wumpo Botan'],
      ['Digtoise', 'Helzephyr'],
      ['Digtoise', 'Grizzbolt'],
      ['Tombat', 'Relaxaurus'],
      ['Tombat', 'Mammorest'],
      ['Tombat', 'Mammorest Cryst'],
      ['Lovander', 'Frostallion Noct'],
      ['Lovander', 'Jetragon'],
      ['Vanwyrm', 'Ragnahawk'],
      ['Vanwyrm', 'Faleris'],
      ['Ragnahawk', 'Blazehowl Noct'],
      ['Katress', 'Warsect'],
      ['Katress', 'Quivern'],
      ['Verdash', 'Suzaku'],
      ['Verdash', 'Shadowbeak'],
      ['Elphidran', 'Azurobe'],
      ['Elphidran Aqua', 'Azurobe'],
      ['Blazehowl', 'Reptyro'],
      ['Blazehowl', 'Warsect'],
      ['Blazehowl Noct', 'Faleris'],
      ['Relaxaurus Lux', 'Petallia'],
      ['Broncherry', 'Helzephyr'],
      ['Broncherry Aqua', 'Helzephyr'],
      ['Broncherry Aqua', 'Grizzbolt'],
      ['Broncherry Aqua', 'Lyleen Noct'],
      ['Petallia', 'Menasting'],
      ['Petallia', 'Lyleen'],
      ['Kingpaca', 'Anubis'],
      ['Wumpo', 'Anubis'],
      ['Wumpo Botan', 'Anubis'],
      ['Fenglope', 'Suzaku'],
      ['Fenglope', 'Shadowbeak'],
      ['Fenglope', 'Necromus'],
      ['Felbat', 'Suzaku Aqua'],
    ],
  },
  {
    pal: 'Jolthog',
    parents: [
      ['Lamball', 'Tanzee'],
      ['Lamball', 'Flopie'],
      ['Lamball', 'Kelpsea'],
      ['Lamball', 'Kelpsea Ignis'],
      ['Cattiva', 'Killamari'],
      ['Cattiva', 'Flopie'],
      ['Cattiva', 'Kelpsea'],
      ['Cattiva', 'Kelpsea Ignis'],
      ['Chikipi', 'Tanzee'],
      ['Chikipi', 'Gumoss'],
      ['Chikipi', 'Gumoss (Special)'],
      ['Chikipi', 'Daedream'],
      ['Chikipi', 'Fuddler'],
      ['Lifmunk', 'Killamari'],
      ['Lifmunk', 'Bristla'],
      ['Lifmunk', 'Ribunny'],
      ['Lifmunk', 'Swee'],
      ['Foxparks', 'Fuack'],
      ['Foxparks', 'Pengullet'],
      ['Foxparks', 'Tocotoco'],
      ['Foxparks', 'Bristla'],
      ['Fuack', 'Sparkit'],
      ['Fuack', 'Hoocrates'],
      ['Fuack', 'Hangyu'],
      ['Fuack', 'Flambelle'],
      ['Sparkit', 'Tocotoco'],
      ['Sparkit', 'Bristla'],
      ['Sparkit', 'Ribunny'],
      ['Tanzee', 'Teafant'],
      ['Tanzee', 'Mau'],
      ['Pengullet', 'Hoocrates'],
      ['Pengullet', 'Depresso'],
      ['Jolthog', 'Jolthog'],
      ['Jolthog', 'Jolthog Cryst'],
      ['Jolthog', 'Depresso'],
      ['Jolthog Cryst', 'Hoocrates'],
      ['Jolthog Cryst', 'Depresso'],
      ['Gumoss', 'Teafant'],
      ['Gumoss', 'Mau'],
      ['Gumoss (Special)', 'Teafant'],
      ['Gumoss (Special)', 'Mau'],
      ['Vixy', 'Killamari'],
      ['Vixy', 'Flopie'],
      ['Vixy', 'Swee'],
      ['Vixy', 'Kelpsea Ignis'],
      ['Hoocrates', 'Tocotoco'],
      ['Teafant', 'Daedream'],
      ['Teafant', 'Kelpsea'],
      ['Depresso', 'Tocotoco'],
      ['Cremis', 'Killamari'],
      ['Cremis', 'Flopie'],
      ['Cremis', 'Kelpsea Ignis'],
      ['Killamari', 'Mau Cryst'],
      ['Mau', 'Kelpsea'],
      ['Mau', 'Kelpsea Ignis'],
      ['Mau Cryst', 'Flopie'],
      ['Mau Cryst', 'Ribunny'],
      ['Mau Cryst', 'Swee'],
      ['Tocotoco', 'Flambelle'],
      ['Bristla', 'Hangyu'],
      ['Bristla', 'Hangyu Cryst'],
      ['Bristla', 'Flambelle'],
      ['Hangyu', 'Ribunny'],
      ['Hangyu Cryst', 'Ribunny'],
      ['Hangyu Cryst', 'Swee'],
    ],
  },
  {
    pal: 'Jolthog Cryst',
    parents: [
      ['Pengullet', 'Jolthog'],
      ['Jolthog Cryst', 'Jolthog Cryst'],
    ],
  },
  {
    pal: 'Gumoss',
    parents: [
      ['Lamball', 'Felbat'],
      ['Cattiva', 'Robinquill'],
      ['Chikipi', 'Fenglope'],
      ['Lifmunk', 'Vaelet'],
      ['Foxparks', 'Cawgnito'],
      ['Fuack', 'Rooby'],
      ['Fuack', 'Maraith'],
      ['Sparkit', 'Beegarde'],
      ['Tanzee', 'Daedream'],
      ['Rooby', 'Bristla'],
      ['Pengullet', 'Rushoar'],
      ['Jolthog', 'Lunaris'],
      ['Jolthog Cryst', 'Leezpunk'],
      ['Gumoss', 'Gumoss'],
      ['Gumoss', 'Gumoss (Special)'],
      ['Vixy', 'Galeclaw'],
      ['Hoocrates', 'Gobfin'],
      ['Teafant', 'Verdash'],
      ['Depresso', 'Gobfin Ignis'],
      ['Cremis', 'Galeclaw'],
      ['Cremis', 'Robinquill'],
      ['Nox', 'Swee'],
      ['Fuddler', 'Kelpsea'],
      ['Killamari', 'Woolipop'],
      ['Mau', 'Robinquill Terra'],
      ['Mau Cryst', 'Gorirat'],
      ['Direhowl', 'Hangyu'],
      ['Direhowl', 'Hangyu Cryst'],
      ['Tocotoco', 'Leezpunk Ignis'],
      ['Bristla', 'Wixen'],
      ['Hangyu Cryst', 'Vaelet'],
      ['Cawgnito', 'Flambelle'],
      ['Beegarde', 'Flambelle'],
      ['Dazzi', 'Kelpsea Ignis'],
    ],
  },
  {
    pal: 'Vixy',
    parents: [
      ['Lamball', 'Lifmunk'],
      ['Lamball', 'Hangyu'],
      ['Lamball', 'Hangyu Cryst'],
      ['Cattiva', 'Lifmunk'],
      ['Cattiva', 'Mau Cryst'],
      ['Cattiva', 'Hangyu Cryst'],
      ['Chikipi', 'Foxparks'],
      ['Chikipi', 'Hoocrates'],
      ['Lifmunk', 'Cremis'],
      ['Foxparks', 'Teafant'],
      ['Sparkit', 'Teafant'],
      ['Sparkit', 'Mau'],
      ['Vixy', 'Vixy'],
      ['Vixy', 'Mau Cryst'],
      ['Teafant', 'Flambelle'],
      ['Cremis', 'Mau Cryst'],
      ['Mau', 'Hangyu'],
      ['Mau', 'Hangyu Cryst'],
      ['Mau', 'Flambelle'],
    ],
  },
  {
    pal: 'Hoocrates',
    parents: [
      ['Lamball', 'Ribunny'],
      ['Cattiva', 'Bristla'],
      ['Chikipi', 'Flopie'],
      ['Lifmunk', 'Pengullet'],
      ['Foxparks', 'Depresso'],
      ['Fuack', 'Vixy'],
      ['Fuack', 'Cremis'],
      ['Sparkit', 'Jolthog'],
      ['Pengullet', 'Hangyu Cryst'],
      ['Jolthog', 'Flambelle'],
      ['Jolthog Cryst', 'Hangyu'],
      ['Jolthog Cryst', 'Hangyu Cryst'],
      ['Hoocrates', 'Hoocrates'],
      ['Teafant', 'Killamari'],
      ['Depresso', 'Flambelle'],
      ['Cremis', 'Bristla'],
      ['Mau', 'Swee'],
      ['Mau Cryst', 'Tocotoco'],
    ],
  },
  {
    pal: 'Teafant',
    parents: [
      ['Chikipi', 'Teafant'],
      ['Chikipi', 'Mau'],
      ['Teafant', 'Teafant'],
    ],
  },
  {
    pal: 'Depresso',
    parents: [
      ['Lamball', 'Killamari'],
      ['Lamball', 'Swee'],
      ['Cattiva', 'Ribunny'],
      ['Cattiva', 'Swee'],
      ['Chikipi', 'Kelpsea'],
      ['Chikipi', 'Kelpsea Ignis'],
      ['Lifmunk', 'Fuack'],
      ['Lifmunk', 'Tocotoco'],
      ['Foxparks', 'Jolthog'],
      ['Foxparks', 'Jolthog Cryst'],
      ['Fuack', 'Mau Cryst'],
      ['Fuack', 'Hangyu Cryst'],
      ['Sparkit', 'Pengullet'],
      ['Sparkit', 'Jolthog Cryst'],
      ['Pengullet', 'Hangyu'],
      ['Pengullet', 'Flambelle'],
      ['Jolthog', 'Hoocrates'],
      ['Jolthog Cryst', 'Flambelle'],
      ['Vixy', 'Bristla'],
      ['Vixy', 'Ribunny'],
      ['Hoocrates', 'Depresso'],
      ['Teafant', 'Flopie'],
      ['Teafant', 'Kelpsea Ignis'],
      ['Depresso', 'Depresso'],
      ['Cremis', 'Ribunny'],
      ['Cremis', 'Swee'],
      ['Killamari', 'Mau'],
      ['Mau', 'Flopie'],
      ['Mau Cryst', 'Bristla'],
      ['Tocotoco', 'Hangyu'],
      ['Tocotoco', 'Hangyu Cryst'],
    ],
  },
  {
    pal: 'Cremis',
    parents: [
      ['Lamball', 'Mau Cryst'],
      ['Cattiva', 'Vixy'],
      ['Chikipi', 'Sparkit'],
      ['Chikipi', 'Flambelle'],
      ['Lifmunk', 'Mau'],
      ['Vixy', 'Cremis'],
      ['Teafant', 'Hangyu'],
      ['Teafant', 'Hangyu Cryst'],
      ['Cremis', 'Cremis'],
    ],
  },
  {
    pal: 'Daedream',
    parents: [
      ['Lamball', 'Robinquill Terra'],
      ['Lamball', 'Verdash'],
      ['Cattiva', 'Robinquill Terra'],
      ['Cattiva', 'Felbat'],
      ['Lifmunk', 'Galeclaw'],
      ['Lifmunk', 'Gorirat'],
      ['Foxparks', 'Direhowl'],
      ['Foxparks', 'Beegarde'],
      ['Fuack', 'Rushoar'],
      ['Fuack', 'Leezpunk Ignis'],
      ['Sparkit', 'Direhowl'],
      ['Sparkit', 'Vaelet'],
      ['Tanzee', 'Fuddler'],
      ['Tanzee', 'Dazzi'],
      ['Rooby', 'Ribunny'],
      ['Rooby', 'Swee'],
      ['Pengullet', 'Leezpunk'],
      ['Pengullet', 'Lunaris'],
      ['Jolthog', 'Gobfin'],
      ['Jolthog', 'Gobfin Ignis'],
      ['Jolthog Cryst', 'Gobfin Ignis'],
      ['Jolthog Cryst', 'Lunaris'],
      ['Gumoss', 'Daedream'],
      ['Gumoss', 'Fuddler'],
      ['Gumoss (Special)', 'Daedream'],
      ['Gumoss (Special)', 'Fuddler'],
      ['Vixy', 'Robinquill'],
      ['Vixy', 'Felbat'],
      ['Hoocrates', 'Cawgnito'],
      ['Hoocrates', 'Beegarde'],
      ['Teafant', 'Fenglope'],
      ['Depresso', 'Gobfin'],
      ['Depresso', 'Cawgnito'],
      ['Cremis', 'Robinquill Terra'],
      ['Cremis', 'Felbat'],
      ['Daedream', 'Daedream'],
      ['Rushoar', 'Tocotoco'],
      ['Nox', 'Killamari'],
      ['Nox', 'Flopie'],
      ['Mau', 'Verdash'],
      ['Mau', 'Fenglope'],
      ['Mau Cryst', 'Galeclaw'],
      ['Mau Cryst', 'Robinquill'],
      ['Direhowl', 'Flambelle'],
      ['Tocotoco', 'Leezpunk'],
      ['Flopie', 'Woolipop'],
      ['Bristla', 'Leezpunk Ignis'],
      ['Bristla', 'Maraith'],
      ['Hangyu', 'Gorirat'],
      ['Hangyu', 'Vaelet'],
      ['Hangyu Cryst', 'Galeclaw'],
      ['Hangyu Cryst', 'Gorirat'],
      ['Woolipop', 'Kelpsea Ignis'],
      ['Ribunny', 'Maraith'],
      ['Ribunny', 'Wixen'],
      ['Swee', 'Wixen'],
      ['Dazzi', 'Kelpsea'],
      ['Flambelle', 'Vaelet'],
    ],
  },
  {
    pal: 'Rushoar',
    parents: [
      ['Lamball', 'Arsox'],
      ['Lamball', 'Chillet'],
      ['Lamball', 'Dinossom Lux'],
      ['Lamball', 'Petallia'],
      ['Cattiva', 'Arsox'],
      ['Cattiva', 'Chillet'],
      ['Cattiva', 'Dinossom'],
      ['Cattiva', 'Dinossom Lux'],
      ['Chikipi', 'Foxcicle'],
      ['Chikipi', 'Tombat'],
      ['Chikipi', 'Petallia'],
      ['Lifmunk', 'Kitsun'],
      ['Lifmunk', 'Dinossom'],
      ['Lifmunk', 'Digtoise'],
      ['Lifmunk', 'Broncherry Aqua'],
      ['Foxparks', 'Celaray'],
      ['Foxparks', 'Reindrix'],
      ['Foxparks', 'Digtoise'],
      ['Foxparks', 'Broncherry'],
      ['Fuack', 'Caprity'],
      ['Fuack', 'Eikthyrdeer'],
      ['Fuack', 'Loupmoon'],
      ['Fuack', 'Lovander'],
      ['Sparkit', 'Celaray'],
      ['Sparkit', 'Digtoise'],
      ['Sparkit', 'Broncherry'],
      ['Sparkit', 'Broncherry Aqua'],
      ['Tanzee', 'Galeclaw'],
      ['Tanzee', 'Robinquill'],
      ['Tanzee', 'Robinquill Terra'],
      ['Tanzee', 'Felbat'],
      ['Rooby', 'Gobfin Ignis'],
      ['Rooby', 'Leezpunk'],
      ['Rooby', 'Lunaris'],
      ['Pengullet', 'Mozzarina'],
      ['Pengullet', 'Caprity'],
      ['Pengullet', 'Eikthyrdeer'],
      ['Pengullet', 'Eikthyrdeer Terra'],
      ['Jolthog', 'Mozzarina'],
      ['Jolthog', 'Melpaca'],
      ['Jolthog', 'Eikthyrdeer Terra'],
      ['Jolthog', 'Dumud'],
      ['Jolthog', 'Reindrix'],
      ['Jolthog Cryst', 'Mozzarina'],
      ['Jolthog Cryst', 'Melpaca'],
      ['Jolthog Cryst', 'Eikthyrdeer'],
      ['Jolthog Cryst', 'Eikthyrdeer Terra'],
      ['Jolthog Cryst', 'Dumud'],
      ['Gumoss', 'Galeclaw'],
      ['Gumoss', 'Robinquill'],
      ['Gumoss', 'Gorirat'],
      ['Gumoss', 'Felbat'],
      ['Gumoss (Special)', 'Galeclaw'],
      ['Gumoss (Special)', 'Robinquill'],
      ['Gumoss (Special)', 'Gorirat'],
      ['Gumoss (Special)', 'Felbat'],
      ['Vixy', 'Chillet'],
      ['Vixy', 'Kitsun'],
      ['Vixy', 'Dinossom'],
      ['Vixy', 'Dinossom Lux'],
      ['Hoocrates', 'Celaray'],
      ['Hoocrates', 'Melpaca'],
      ['Hoocrates', 'Reindrix'],
      ['Hoocrates', 'Broncherry'],
      ['Teafant', 'Arsox'],
      ['Teafant', 'Foxcicle'],
      ['Teafant', 'Petallia'],
      ['Depresso', 'Celaray'],
      ['Depresso', 'Melpaca'],
      ['Depresso', 'Eikthyrdeer Terra'],
      ['Depresso', 'Dumud'],
      ['Depresso', 'Reindrix'],
      ['Cremis', 'Chillet'],
      ['Cremis', 'Dinossom'],
      ['Cremis', 'Dinossom Lux'],
      ['Daedream', 'Galeclaw'],
      ['Daedream', 'Robinquill'],
      ['Daedream', 'Gorirat'],
      ['Daedream', 'Vaelet'],
      ['Rushoar', 'Rushoar'],
      ['Rushoar', 'Leezpunk'],
      ['Rushoar', 'Leezpunk Ignis'],
      ['Rushoar', 'Maraith'],
      ['Nox', 'Gobfin'],
      ['Nox', 'Gobfin Ignis'],
      ['Nox', 'Cawgnito'],
      ['Nox', 'Beegarde'],
      ['Fuddler', 'Direhowl'],
      ['Fuddler', 'Galeclaw'],
      ['Fuddler', 'Gorirat'],
      ['Fuddler', 'Vaelet'],
      ['Killamari', 'Verdash'],
      ['Killamari', 'Fenglope'],
      ['Mau', 'Arsox'],
      ['Mau', 'Chillet'],
      ['Mau', 'Petallia'],
      ['Mau Cryst', 'Kitsun'],
      ['Mau Cryst', 'Dinossom'],
      ['Mau Cryst', 'Dinossom Lux'],
      ['Mau Cryst', 'Broncherry Aqua'],
      ['Celaray', 'Flambelle'],
      ['Direhowl', 'Woolipop'],
      ['Direhowl', 'Dazzi'],
      ['Tocotoco', 'Mozzarina'],
      ['Tocotoco', 'Caprity'],
      ['Tocotoco', 'Eikthyrdeer'],
      ['Tocotoco', 'Lovander'],
      ['Flopie', 'Robinquill Terra'],
      ['Flopie', 'Verdash'],
      ['Flopie', 'Fenglope'],
      ['Bristla', 'Caprity'],
      ['Bristla', 'Loupmoon'],
      ['Bristla', 'Lovander'],
      ['Gobfin', 'Woolipop'],
      ['Gobfin', 'Wixen'],
      ['Gobfin Ignis', 'Maraith'],
      ['Gobfin Ignis', 'Wixen'],
      ['Hangyu', 'Kitsun'],
      ['Hangyu', 'Digtoise'],
      ['Hangyu', 'Broncherry'],
      ['Hangyu', 'Broncherry Aqua'],
      ['Hangyu Cryst', 'Kitsun'],
      ['Hangyu Cryst', 'Digtoise'],
      ['Hangyu Cryst', 'Broncherry Aqua'],
      ['Woolipop', 'Cawgnito'],
      ['Woolipop', 'Beegarde'],
      ['Ribunny', 'Loupmoon'],
      ['Ribunny', 'Lovander'],
      ['Leezpunk', 'Leezpunk Ignis'],
      ['Leezpunk', 'Maraith'],
      ['Leezpunk', 'Wixen'],
      ['Leezpunk Ignis', 'Lunaris'],
      ['Loupmoon', 'Swee'],
      ['Robinquill', 'Kelpsea'],
      ['Robinquill Terra', 'Kelpsea'],
      ['Robinquill Terra', 'Kelpsea Ignis'],
      ['Gorirat', 'Dazzi'],
      ['Beegarde', 'Dazzi'],
      ['Swee', 'Fenglope'],
      ['Dazzi', 'Vaelet'],
      ['Lunaris', 'Maraith'],
      ['Lunaris', 'Wixen'],
      ['Digtoise', 'Flambelle'],
      ['Flambelle', 'Broncherry'],
      ['Verdash', 'Kelpsea'],
      ['Verdash', 'Kelpsea Ignis'],
      ['Kelpsea', 'Felbat'],
      ['Kelpsea Ignis', 'Fenglope'],
      ['Kelpsea Ignis', 'Felbat'],
    ],
  },
  {
    pal: 'Nox',
    parents: [
      ['Lamball', 'Melpaca'],
      ['Lamball', 'Dumud'],
      ['Lamball', 'Reindrix'],
      ['Cattiva', 'Melpaca'],
      ['Cattiva', 'Eikthyrdeer Terra'],
      ['Cattiva', 'Dumud'],
      ['Chikipi', 'Digtoise'],
      ['Chikipi', 'Broncherry'],
      ['Lifmunk', 'Caprity'],
      ['Lifmunk', 'Eikthyrdeer'],
      ['Foxparks', 'Loupmoon'],
      ['Fuack', 'Galeclaw'],
      ['Fuack', 'Robinquill'],
      ['Sparkit', 'Loupmoon'],
      ['Sparkit', 'Lovander'],
      ['Tanzee', 'Gobfin Ignis'],
      ['Tanzee', 'Lunaris'],
      ['Rooby', 'Woolipop'],
      ['Rooby', 'Dazzi'],
      ['Pengullet', 'Robinquill Terra'],
      ['Pengullet', 'Felbat'],
      ['Jolthog', 'Verdash'],
      ['Jolthog', 'Fenglope'],
      ['Jolthog Cryst', 'Robinquill Terra'],
      ['Jolthog Cryst', 'Verdash'],
      ['Gumoss', 'Leezpunk'],
      ['Gumoss', 'Lunaris'],
      ['Gumoss (Special)', 'Leezpunk'],
      ['Gumoss (Special)', 'Lunaris'],
      ['Vixy', 'Mozzarina'],
      ['Vixy', 'Eikthyrdeer Terra'],
      ['Vixy', 'Dumud'],
      ['Teafant', 'Celaray'],
      ['Teafant', 'Broncherry'],
      ['Depresso', 'Fenglope'],
      ['Cremis', 'Mozzarina'],
      ['Cremis', 'Melpaca'],
      ['Cremis', 'Eikthyrdeer Terra'],
      ['Cremis', 'Dumud'],
      ['Daedream', 'Rushoar'],
      ['Daedream', 'Leezpunk'],
      ['Rushoar', 'Fuddler'],
      ['Nox', 'Nox'],
      ['Fuddler', 'Leezpunk Ignis'],
      ['Killamari', 'Direhowl'],
      ['Killamari', 'Beegarde'],
      ['Mau', 'Celaray'],
      ['Mau', 'Reindrix'],
      ['Mau Cryst', 'Mozzarina'],
      ['Mau Cryst', 'Eikthyrdeer'],
      ['Direhowl', 'Swee'],
      ['Tocotoco', 'Robinquill'],
      ['Tocotoco', 'Felbat'],
      ['Flopie', 'Cawgnito'],
      ['Flopie', 'Beegarde'],
      ['Bristla', 'Galeclaw'],
      ['Bristla', 'Gorirat'],
      ['Gobfin', 'Kelpsea'],
      ['Gobfin', 'Kelpsea Ignis'],
      ['Gobfin Ignis', 'Kelpsea'],
      ['Hangyu', 'Caprity'],
      ['Hangyu', 'Lovander'],
      ['Hangyu Cryst', 'Caprity'],
      ['Hangyu Cryst', 'Eikthyrdeer'],
      ['Hangyu Cryst', 'Lovander'],
      ['Woolipop', 'Wixen'],
      ['Ribunny', 'Gorirat'],
      ['Ribunny', 'Vaelet'],
      ['Cawgnito', 'Kelpsea Ignis'],
      ['Leezpunk Ignis', 'Dazzi'],
      ['Loupmoon', 'Flambelle'],
      ['Swee', 'Vaelet'],
      ['Dazzi', 'Maraith'],
      ['Lovander', 'Flambelle'],
    ],
  },
  {
    pal: 'Fuddler',
    parents: [
      ['Lamball', 'Fenglope'],
      ['Cattiva', 'Verdash'],
      ['Cattiva', 'Fenglope'],
      ['Chikipi', 'Loupmoon'],
      ['Chikipi', 'Lovander'],
      ['Lifmunk', 'Robinquill'],
      ['Lifmunk', 'Felbat'],
      ['Foxparks', 'Gorirat'],
      ['Foxparks', 'Vaelet'],
      ['Fuack', 'Leezpunk'],
      ['Fuack', 'Lunaris'],
      ['Sparkit', 'Galeclaw'],
      ['Sparkit', 'Gorirat'],
      ['Tanzee', 'Woolipop'],
      ['Rooby', 'Killamari'],
      ['Rooby', 'Flopie'],
      ['Pengullet', 'Gobfin'],
      ['Pengullet', 'Gobfin Ignis'],
      ['Jolthog', 'Cawgnito'],
      ['Jolthog', 'Beegarde'],
      ['Jolthog Cryst', 'Gobfin'],
      ['Jolthog Cryst', 'Cawgnito'],
      ['Gumoss', 'Dazzi'],
      ['Gumoss (Special)', 'Dazzi'],
      ['Vixy', 'Robinquill Terra'],
      ['Vixy', 'Verdash'],
      ['Hoocrates', 'Direhowl'],
      ['Hoocrates', 'Vaelet'],
      ['Teafant', 'Loupmoon'],
      ['Depresso', 'Direhowl'],
      ['Depresso', 'Beegarde'],
      ['Cremis', 'Verdash'],
      ['Cremis', 'Fenglope'],
      ['Daedream', 'Fuddler'],
      ['Daedream', 'Dazzi'],
      ['Rushoar', 'Bristla'],
      ['Rushoar', 'Ribunny'],
      ['Nox', 'Kelpsea'],
      ['Nox', 'Kelpsea Ignis'],
      ['Fuddler', 'Fuddler'],
      ['Killamari', 'Maraith'],
      ['Killamari', 'Wixen'],
      ['Mau Cryst', 'Robinquill Terra'],
      ['Mau Cryst', 'Felbat'],
      ['Tocotoco', 'Gobfin Ignis'],
      ['Tocotoco', 'Lunaris'],
      ['Flopie', 'Wixen'],
      ['Bristla', 'Leezpunk'],
      ['Hangyu', 'Galeclaw'],
      ['Hangyu', 'Robinquill'],
      ['Hangyu Cryst', 'Robinquill'],
      ['Hangyu Cryst', 'Felbat'],
      ['Woolipop', 'Kelpsea'],
      ['Ribunny', 'Leezpunk Ignis'],
      ['Leezpunk Ignis', 'Swee'],
      ['Galeclaw', 'Flambelle'],
      ['Gorirat', 'Flambelle'],
      ['Swee', 'Maraith'],
    ],
  },
  { pal: 'Killamari' },
  { pal: 'Mau' },
  { pal: 'Mau Cryst' },
  { pal: 'Celaray' },
  { pal: 'Direhowl' },
  { pal: 'Tocotoco' },
  { pal: 'Flopie' },
  { pal: 'Mozzarina' },
  { pal: 'Bristla' },
  { pal: 'Gobfin' },
  { pal: 'Gobfin Ignis' },
  { pal: 'Hangyu' },
  { pal: 'Hangyu Cryst' },
  { pal: 'Mossanda' },
  { pal: 'Mossanda Lux' },
  { pal: 'Woolipop' },
  { pal: 'Caprity' },
  { pal: 'Melpaca' },
  { pal: 'Eikthyrdeer' },
  { pal: 'Eikthyrdeer Terra' },
  { pal: 'Nitewing' },
  { pal: 'Ribunny' },
  { pal: 'Incineram' },
  { pal: 'Incineram Noct' },
  { pal: 'Cinnamoth' },
  { pal: 'Arsox' },
  { pal: 'Dumud' },
  { pal: 'Cawgnito' },
  { pal: 'Leezpunk' },
  { pal: 'Leezpunk Ignis' },
  { pal: 'Loupmoon' },
  { pal: 'Galeclaw' },
  { pal: 'Robinquill' },
  { pal: 'Robinquill Terra' },
  { pal: 'Gorirat' },
  { pal: 'Beegarde' },
  { pal: 'Elizabee' },
  { pal: 'Grintale' },
  { pal: 'Swee' },
  { pal: 'Sweepa' },
  { pal: 'Chillet' },
  { pal: 'Univolt' },
  { pal: 'Foxcicle' },
  { pal: 'Pyrin' },
  { pal: 'Pyrin Noct' },
  { pal: 'Reindrix' },
  { pal: 'Rayhound' },
  { pal: 'Kitsun' },
  { pal: 'Dazzi' },
  { pal: 'Lunaris' },
  { pal: 'Dinossom' },
  { pal: 'Dinossom Lux' },
  { pal: 'Surfent' },
  { pal: 'Surfent Terra' },
  { pal: 'Maraith' },
  { pal: 'Digtoise' },
  { pal: 'Tombat' },
  { pal: 'Lovander' },
  { pal: 'Flambelle' },
  { pal: 'Vanwyrm' },
  { pal: 'Vanwyrm Cryst' },
  { pal: 'Bushi' },
  { pal: 'Beakon' },
  { pal: 'Ragnahawk' },
  { pal: 'Katress' },
  { pal: 'Wixen' },
  { pal: 'Verdash' },
  { pal: 'Vaelet' },
  { pal: 'Sibelyx' },
  { pal: 'Elphidran' },
  { pal: 'Elphidran Aqua' },
  { pal: 'Kelpsea' },
  { pal: 'Kelpsea Ignis' },
  { pal: 'Azurobe' },
  { pal: 'Cryolinx' },
  { pal: 'Blazehowl' },
  { pal: 'Blazehowl Noct' },
  { pal: 'Relaxaurus' },
  { pal: 'Relaxaurus Lux' },
  { pal: 'Broncherry' },
  { pal: 'Broncherry Aqua' },
  { pal: 'Petallia' },
  { pal: 'Reptyro' },
  { pal: 'Ice Reptyro' },
  { pal: 'Kingpaca' },
  { pal: 'Ice Kingpaca' },
  { pal: 'Mammorest' },
  { pal: 'Mammorest Cryst' },
  { pal: 'Wumpo' },
  { pal: 'Wumpo Botan' },
  { pal: 'Warsect' },
  { pal: 'Fenglope' },
  { pal: 'Felbat' },
  { pal: 'Quivern' },
  { pal: 'Blazamut' },
  { pal: 'Helzephyr' },
  { pal: 'Astegon' },
  { pal: 'Menasting' },
  { pal: 'Anubis' },
  { pal: 'Jormuntide' },
  { pal: 'Jormuntide Ignis' },
  { pal: 'Suzaku' },
  { pal: 'Suzaku Aqua' },
  { pal: 'Grizzbolt' },
  { pal: 'Lyleen' },
  { pal: 'Lyleen Noct' },
  { pal: 'Faleris' },
  { pal: 'Orserk' },
  { pal: 'Shadowbeak' },
  { pal: 'Paladius' },
  { pal: 'Necromus' },
  { pal: 'Frostallion' },
  { pal: 'Frostallion Noct' },
  { pal: 'Jetragon' },
]

export const elements = [
  { name: 'dark', value: 'dark', srcImage: '/icon/element/dark.webp' },
  { name: 'dragon', value: 'dragon', srcImage: '/icon/element/dragon.webp' },
  {
    name: 'electric',
    value: 'electric',
    srcImage: '/icon/element/electric.webp',
  },
  { name: 'fire', value: 'fire', srcImage: '/icon/element/fire.webp' },
  { name: 'grass', value: 'grass', srcImage: '/icon/element/grass.webp' },
  { name: 'ground', value: 'ground', srcImage: '/icon/element/ground.webp' },
  { name: 'ice', value: 'ice', srcImage: '/icon/element/ice.webp' },
  { name: 'neutral', value: 'neutral', srcImage: '/icon/element/neutral.webp' },
  { name: 'water', value: 'water', srcImage: '/icon/element/water.webp' },
]

export const workSuitability = [
  { name: 'cooling', value: 'cooling', srcImage: '/icon/work/cooling.webp' },
  { name: 'farming', value: 'farming', srcImage: '/icon/work/farming.webp' },
  {
    name: 'gathering',
    value: 'gathering',
    srcImage: '/icon/work/gathering.webp',
  },
  {
    name: 'generate electricity',
    value: 'generatingElectricity',
    srcImage: '/icon/work/generatingElectricity.webp',
  },
  {
    name: 'handiwork',
    value: 'handiwork',
    srcImage: '/icon/work/handiwork.webp',
  },
  { name: 'kindling', value: 'kindling', srcImage: '/icon/work/kindling.webp' },
  {
    name: 'lumbering',
    value: 'lumbering',
    srcImage: '/icon/work/lumbering.webp',
  },
  {
    name: 'medicine production',
    value: 'medicineProduction',
    srcImage: '/icon/work/medicineProduction.webp',
  },
  { name: 'mining', value: 'mining', srcImage: '/icon/work/mining.webp' },
  { name: 'planting', value: 'planting', srcImage: '/icon/work/planting.webp' },
  {
    name: 'transporting',
    value: 'transporting',
    srcImage: '/icon/work/transporting.webp',
  },
  { name: 'watering', value: 'watering', srcImage: '/icon/work/watering.webp' },
]
