type IPals = {
  id: string
  name: string
  number: string
  caught: string
  element: (
    | 'dark'
    | 'dragon'
    | 'electric'
    | 'fire'
    | 'grass'
    | 'ground'
    | 'ice'
    | 'neutral'
    | 'water'
  )[]
  workSkill: {
    skill:
      | 'cooling'
      | 'farming'
      | 'gathering'
      | 'generatingElectricity'
      | 'handiwork'
      | 'kindling'
      | 'lumbering'
      | 'medicineProduction'
      | 'mining'
      | 'planting'
      | 'transporting'
      | 'watering'
    lv: '1' | '2' | '3' | '4'
  }[]
  searchFilter: string
  image: string
}[]

export const pals: IPals = [
  {
    id: crypto.randomUUID(),
    name: 'Lamball',
    number: '1',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'farming', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: 'Lamball',
    image: '/pal/icon/lamball.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Cattiva',
    number: '2',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'mining', lv: '1' },
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/cattiva.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Chikipi',
    number: '3',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'farming', lv: '1' },
      { skill: 'gathering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/chikipi.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Lifmunk',
    number: '4',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'lumbering', lv: '1' },
      { skill: 'medicineProduction', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/lifmunk.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Foxparks',
    number: '5',
    caught: '0',
    element: ['fire'],
    workSkill: [{ skill: 'kindling', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/foxparks.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Fuack',
    number: '6',
    caught: '0',
    element: ['water'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'watering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/fuack.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Sparkit',
    number: '7',
    caught: '0',
    element: ['electric'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'generatingElectricity', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/sparkit.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Tanzee',
    number: '8',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '1' },
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'lumbering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/tanzee.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Rooby',
    number: '9',
    caught: '0',
    element: ['fire'],
    workSkill: [{ skill: 'kindling', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/sparkit.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Pengullet',
    number: '10',
    caught: '0',
    element: ['water', 'ice'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'watering', lv: '1' },
      { skill: 'cooling', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/pengullet.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Penking',
    number: '11',
    caught: '0',
    element: ['water', 'ice'],
    workSkill: [
      { skill: 'mining', lv: '2' },
      { skill: 'transporting', lv: '2' },
      { skill: 'watering', lv: '2' },
      { skill: 'cooling', lv: '2' },
      { skill: 'handiwork', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/penking.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jolthog',
    number: '12',
    caught: '0',
    element: ['electric'],
    workSkill: [{ skill: 'generatingElectricity', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/jolthog.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jolthog Cryst',
    number: '12B',
    caught: '0',
    element: ['ice'],
    workSkill: [{ skill: 'cooling', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/jolthogCryst.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Gumoss',
    number: '13',
    caught: '0',
    element: ['grass', 'ground'],
    workSkill: [{ skill: 'planting', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/gumoss.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Vixy',
    number: '14',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'farming', lv: '1' },
      { skill: 'gathering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/vixy.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Hoocrates',
    number: '15',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'gathering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/hoocrates.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Teafant',
    number: '16',
    caught: '0',
    element: ['water'],
    workSkill: [{ skill: 'watering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/teafant.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Depresso',
    number: '17',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'mining', lv: '1' },
      { skill: 'transporting', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/depresso.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Cremis',
    number: '18',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'farming', lv: '1' },
      { skill: 'gathering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/cremis.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Daedream',
    number: '19',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/daedream.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Rushoar',
    number: '20',
    caught: '0',
    element: ['ground'],
    workSkill: [{ skill: 'mining', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/rushoar.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Nox',
    number: '21',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'gathering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/nox.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Fuddler',
    number: '22',
    caught: '0',
    element: ['ground'],
    workSkill: [
      { skill: 'mining', lv: '1' },
      { skill: 'transporting', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/fuddler.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Killamari',
    number: '23',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'transporting', lv: '2' },
      { skill: 'gathering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/killamari.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Mau',
    number: '24',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'farming', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/mau.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Mau Cryst',
    number: '24B',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'cooling', lv: '1' },
      { skill: 'farming', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/mauCryst.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Celaray',
    number: '25',
    caught: '0',
    element: ['water'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'watering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/celaray.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Direhowl',
    number: '26',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'gathering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/direhowl.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Tocotoco',
    number: '27',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'gathering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/tocotoco.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Flopie',
    number: '28',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '1' },
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'medicineProduction', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/flopie.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Mozzarina',
    number: '29',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'farming', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/mozzarina.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Bristla',
    number: '30',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '1' },
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'medicineProduction', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/bristla.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Gobfin',
    number: '31',
    caught: '0',
    element: ['water'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'watering', lv: '2' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/gobfin.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Gobfin Ignis',
    number: '31B',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'kindling', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/gobfinIgnis.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Hangyu',
    number: '32',
    caught: '0',
    element: ['ground'],
    workSkill: [
      { skill: 'transporting', lv: '2' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/hangyu.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Hangyu Cryst',
    number: '32B',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'transporting', lv: '2' },
      { skill: 'cooling', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/hangyuCryst.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Mossanda',
    number: '33',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '2' },
      { skill: 'transporting', lv: '3' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/mossanda.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Mossanda Lux',
    number: '33B',
    caught: '0',
    element: ['electric'],
    workSkill: [
      { skill: 'transporting', lv: '3' },
      { skill: 'generatingElectricity', lv: '2' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/mossandaLux.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Woolipop',
    number: '34',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'farming', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/woolipop.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Caprity',
    number: '35',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '2' },
      { skill: 'farming', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/caprity.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Melpaca',
    number: '36',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'farming', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/melpaca.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Eikthyrdeer',
    number: '37',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'lumbering', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/eikthyrdeer.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Eikthyrdeer Terra',
    number: '37B',
    caught: '0',
    element: ['ground'],
    workSkill: [{ skill: 'lumbering', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/eikthyrdeerTerra.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Nitewing',
    number: '38',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'gathering', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/nitewing.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Ribbuny',
    number: '39',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/ribbuny.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Incineram',
    number: '40',
    caught: '0',
    element: ['fire', 'dark'],
    workSkill: [
      { skill: 'mining', lv: '1' },
      { skill: 'transporting', lv: '2' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'kindling', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/incineram.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Incineram Noct',
    number: '40B',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'mining', lv: '1' },
      { skill: 'transporting', lv: '2' },
      { skill: 'handiwork', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/incineramNoct.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Cinnamoth',
    number: '41',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '2' },
      { skill: 'medicineProduction', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/cinnamoth.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Arsox',
    number: '42',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'kindling', lv: '2' },
      { skill: 'lumbering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/arsox.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Dumud',
    number: '43',
    caught: '0',
    element: ['ground'],
    workSkill: [
      { skill: 'mining', lv: '2' },
      { skill: 'transporting', lv: '1' },
      { skill: 'watering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/dumud.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Cawgnito',
    number: '44',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'lumbering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/cawgnito.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Leezpunk',
    number: '45',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/leezpunk.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Leezpunk Ignis',
    number: '45B',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'kindling', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/leezpunkIgnis.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Loupmoon',
    number: '46',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'handiwork', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/loupmoon.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Galeclaw',
    number: '47',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'gathering', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/galeclaw.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Robinquill',
    number: '48',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '1' },
      { skill: 'transporting', lv: '2' },
      { skill: 'gathering', lv: '2' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'lumbering', lv: '1' },
      { skill: 'medicineProduction', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/robinquill.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Robinquill Terra',
    number: '48B',
    caught: '0',
    element: ['grass', 'ground'],
    workSkill: [
      { skill: 'transporting', lv: '2' },
      { skill: 'gathering', lv: '2' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'lumbering', lv: '1' },
      { skill: 'medicineProduction', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/robinquillTerra.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Gorirat',
    number: '49',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'transporting', lv: '3' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/gorirat.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Beegarde',
    number: '50',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '1' },
      { skill: 'transporting', lv: '2' },
      { skill: 'farming', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'lumbering', lv: '1' },
      { skill: 'medicineProduction', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/beegarde.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Elizabee',
    number: '51',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '2' },
      { skill: 'gathering', lv: '2' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'lumbering', lv: '1' },
      { skill: 'medicineProduction', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/elizabee.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Grintale',
    number: '52',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'gathering', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/grintale.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Swee',
    number: '53',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'cooling', lv: '1' },
      { skill: 'gathering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/swee.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Sweepa',
    number: '54',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'cooling', lv: '2' },
      { skill: 'gathering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/sweepa.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Chillet',
    number: '55',
    caught: '0',
    element: ['ice', 'dragon'],
    workSkill: [
      { skill: 'cooling', lv: '1' },
      { skill: 'gathering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/chillet.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Univolt',
    number: '56',
    caught: '0',
    element: ['electric'],
    workSkill: [
      { skill: 'generatingElectricity', lv: '2' },
      { skill: 'lumbering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/univolt.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Foxcicle',
    number: '57',
    caught: '0',
    element: ['ice'],
    workSkill: [{ skill: 'cooling', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/foxcicle.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Pyrin',
    number: '58',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'kindling', lv: '2' },
      { skill: 'lumbering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/pyrin.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Pyrin Noct',
    number: '58B',
    caught: '0',
    element: ['fire', 'dark'],
    workSkill: [
      { skill: 'kindling', lv: '2' },
      { skill: 'lumbering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/pyrinNoct.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Reindrix',
    number: '59',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'cooling', lv: '2' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/reindrix.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Rayhound',
    number: '60',
    caught: '0',
    element: ['electric'],
    workSkill: [{ skill: 'generatingElectricity', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/rayhound.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Kitsun',
    number: '61',
    caught: '0',
    element: ['fire'],
    workSkill: [{ skill: 'kindling', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/kitsun.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Dazzi',
    number: '62',
    caught: '0',
    element: ['electric'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'generatingElectricity', lv: '1' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/dazzi.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Lunaris',
    number: '63',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/lunaris.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Dinossom',
    number: '',
    caught: '0',
    element: ['grass', 'dragon'],
    workSkill: [
      { skill: 'planting', lv: '2' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/Dinossom.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Dinossom Lux',
    number: '64B',
    caught: '0',
    element: ['electric', 'dragon'],
    workSkill: [
      { skill: 'generatingElectricity', lv: '2' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/dinossomLux.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Surfent',
    number: '65',
    caught: '0',
    element: ['water'],
    workSkill: [{ skill: 'watering', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/surfent.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Surfent Terra',
    number: '65B',
    caught: '0',
    element: ['ground'],
    workSkill: [{ skill: 'gathering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/surfentTerra.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Maraith',
    number: '66',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'mining', lv: '1' },
      { skill: 'gathering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/maraith.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Digtoise',
    number: '67',
    caught: '0',
    element: ['ground'],
    workSkill: [{ skill: 'mining', lv: '3' }],
    searchFilter: '',
    image: '/pal/icon/digtoise.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Tombat',
    number: '68',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'mining', lv: '2' },
      { skill: 'transporting', lv: '2' },
      { skill: 'gathering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/tombat.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Lovander',
    number: '69',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'mining', lv: '1' },
      { skill: 'transporting', lv: '2' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'medicineProduction', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/lovander.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Flambelle',
    number: '70',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'farming', lv: '1' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'kindling', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/flambelle.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Vanwyrm',
    number: '71',
    caught: '0',
    element: ['fire', 'dark'],
    workSkill: [
      { skill: 'transporting', lv: '3' },
      { skill: 'kindling', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/vanwyrm.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Vanwyrm Cryst',
    number: '71B',
    caught: '0',
    element: ['ice', 'dark'],
    workSkill: [
      { skill: 'transporting', lv: '3' },
      { skill: 'cooling', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/vanwyrmCryst.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Bushi',
    number: '72',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'transporting', lv: '2' },
      { skill: 'gathering', lv: '1' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'kindling', lv: '2' },
      { skill: 'lumbering', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/bushi.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Beakon',
    number: '73',
    caught: '0',
    element: ['electric'],
    workSkill: [
      { skill: 'transporting', lv: '3' },
      { skill: 'gathering', lv: '1' },
      { skill: 'generatingElectricity', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/beakon.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Ragnahawk',
    number: '74',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'transporting', lv: '3' },
      { skill: 'kindling', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/ragnahawk.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Katress',
    number: '75',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'transporting', lv: '2' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'medicineProduction', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/katress.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Wixen',
    number: '76',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'transporting', lv: '2' },
      { skill: 'handiwork', lv: '3' },
      { skill: 'kindling', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/wixen.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Verdash',
    number: '77',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '2' },
      { skill: 'transporting', lv: '2' },
      { skill: 'gathering', lv: '3' },
      { skill: 'handiwork', lv: '3' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/verdash.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Vaelet',
    number: '78',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '2' },
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '2' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'medicineProduction', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/vaelet.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Sibelyx',
    number: '79',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'cooling', lv: '2' },
      { skill: 'farming', lv: '1' },
      { skill: 'medicineProduction', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/sibelyx.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Elphidran',
    number: '80',
    caught: '0',
    element: ['dragon'],
    workSkill: [{ skill: 'lumbering', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/elphidran.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Elphidran Aqua',
    number: '80B',
    caught: '0',
    element: ['dragon', 'water'],
    workSkill: [
      { skill: 'watering', lv: '3' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/elphidranAqua.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Kelpsea',
    number: '81',
    caught: '0',
    element: ['water'],
    workSkill: [{ skill: 'watering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/kelpsea.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Kelpsea Ignis',
    number: '81B',
    caught: '0',
    element: ['fire'],
    workSkill: [{ skill: 'kindling', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/kelpseaIgnis.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Azurobe',
    number: '82',
    caught: '0',
    element: ['water', 'dragon'],
    workSkill: [{ skill: 'watering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/azurobe.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Cryolinx',
    number: '83',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'cooling', lv: '3' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/cryolinx.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Blazehowl',
    number: '84',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'kindling', lv: '3' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/blazehowl.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Blazehowl Noct',
    number: '84B',
    caught: '0',
    element: ['fire', 'dark'],
    workSkill: [
      { skill: 'kindling', lv: '3' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/blazehowlNoct.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Relaxaurus',
    number: '85',
    caught: '0',
    element: ['dragon', 'water'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'watering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/relaxaurus.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Relaxaurus Lux',
    number: '85B',
    caught: '0',
    element: ['dragon', 'electric'],
    workSkill: [
      { skill: 'transporting', lv: '1' },
      { skill: 'generatingElectricity', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/relaxaurusLux.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Broncherry',
    number: '',
    caught: '0',
    element: ['grass'],
    workSkill: [{ skill: 'planting', lv: '3' }],
    searchFilter: '',
    image: '/pal/icon/broncherry.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Broncherry Aqua',
    number: '86B',
    caught: '0',
    element: ['grass', 'water'],
    workSkill: [{ skill: 'watering', lv: '3' }],
    searchFilter: '',
    image: '/pal/icon/broncherryAqua.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Petallia',
    number: '87',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '3' },
      { skill: 'transporting', lv: '1' },
      { skill: 'gathering', lv: '2' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'medicineProduction', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/petallia.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Reptyro',
    number: '88',
    caught: '0',
    element: ['fire', 'ground'],
    workSkill: [
      { skill: 'mining', lv: '3' },
      { skill: 'kindling', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/reptyro.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Ice Reptyro',
    number: '88B',
    caught: '0',
    element: ['ice', 'ground'],
    workSkill: [
      { skill: 'mining', lv: '3' },
      { skill: 'cooling', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/iceReptyro.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Kingpaca',
    number: '89',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'gathering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/kingpaca.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Ice Kingpaca',
    number: '89B',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'cooling', lv: '3' },
      { skill: 'gathering', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/iceKingpaca.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Mammorest',
    number: '90',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'mining', lv: '2' },
      { skill: 'planting', lv: '2' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/mammorest.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Mammorest Cryst',
    number: '90B',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'mining', lv: '2' },
      { skill: 'cooling', lv: '2' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/mammorestCryst.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Wumpo',
    number: '91',
    caught: '0',
    element: ['ice'],
    workSkill: [
      { skill: 'transporting', lv: '4' },
      { skill: 'cooling', lv: '2' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'lumbering', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/wumpo.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Wumpo Botan',
    number: '91B',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '1' },
      { skill: 'transporting', lv: '4' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'lumbering', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/wumpoBotan.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Warsect',
    number: '92',
    caught: '0',
    element: ['ground', 'grass'],
    workSkill: [
      { skill: 'planting', lv: '1' },
      { skill: 'transporting', lv: '3' },
      { skill: 'handiwork', lv: '1' },
      { skill: 'lumbering', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/warsect.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Fenglope',
    number: '93',
    caught: '0',
    element: ['neutral'],
    workSkill: [{ skill: 'lumbering', lv: '2' }],
    searchFilter: '',
    image: '/pal/icon/fenglope.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Felbat',
    number: '94',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'medicineProduction', lv: '3' }],
    searchFilter: '',
    image: '/pal/icon/felbat.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Quivern',
    number: '95',
    caught: '0',
    element: ['dragon'],
    workSkill: [
      { skill: 'mining', lv: '2' },
      { skill: 'transporting', lv: '3' },
      { skill: 'gathering', lv: '2' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/quivern.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Blazamut',
    number: '96',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'mining', lv: '4' },
      { skill: 'kindling', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/blazamut.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Helzephyr',
    number: '97',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'transporting', lv: '3' }],
    searchFilter: '',
    image: '/pal/icon/helzephyr.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Astegon',
    number: '98',
    caught: '0',
    element: ['dragon', 'dark'],
    workSkill: [
      { skill: 'mining', lv: '4' },
      { skill: 'handiwork', lv: '1' },
    ],
    searchFilter: '',
    image: '/pal/icon/astegon.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Menasting',
    number: '99',
    caught: '0',
    element: ['dark', 'ground'],
    workSkill: [
      { skill: 'mining', lv: '3' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/menasting.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Anubis',
    number: '100',
    caught: '0',
    element: ['ground'],
    workSkill: [
      { skill: 'mining', lv: '3' },
      { skill: 'transporting', lv: '2' },
      { skill: 'handiwork', lv: '4' },
    ],
    searchFilter: '',
    image: '/pal/icon/anubis.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jormuntide',
    number: '101',
    caught: '0',
    element: ['dragon', 'water'],
    workSkill: [{ skill: 'watering', lv: '4' }],
    searchFilter: '',
    image: '/pal/icon/jormuntide.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jormuntide Ignis',
    number: '101B',
    caught: '0',
    element: ['dragon', 'fire'],
    workSkill: [{ skill: 'kindling', lv: '4' }],
    searchFilter: '',
    image: '/pal/icon/jormuntideIgnis.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Suzaku',
    number: '102',
    caught: '0',
    element: ['fire'],
    workSkill: [{ skill: 'kindling', lv: '3' }],
    searchFilter: '',
    image: '/pal/icon/suzaku.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Suzaku Aqua',
    number: '102B',
    caught: '0',
    element: ['water'],
    workSkill: [{ skill: 'watering', lv: '3' }],
    searchFilter: '',
    image: '/pal/icon/suzakuAqua.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Grizzbolt',
    number: '103',
    caught: '0',
    element: ['electric'],
    workSkill: [
      { skill: 'transporting', lv: '3' },
      { skill: 'generatingElectricity', lv: '3' },
      { skill: 'handiwork', lv: '2' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/grizzbolt.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Lyleen',
    number: '104',
    caught: '0',
    element: ['grass'],
    workSkill: [
      { skill: 'planting', lv: '4' },
      { skill: 'gathering', lv: '2' },
      { skill: 'handiwork', lv: '3' },
      { skill: 'medicineProduction', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/lyleen.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Lyleen Noct',
    number: '104B',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'gathering', lv: '2' },
      { skill: 'handiwork', lv: '3' },
      { skill: 'medicineProduction', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/lyleenNoct.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Faleris',
    number: '105',
    caught: '0',
    element: ['fire'],
    workSkill: [
      { skill: 'transporting', lv: '3' },
      { skill: 'kindling', lv: '3' },
    ],
    searchFilter: '',
    image: '/pal/icon/faleris.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Orserk',
    number: '106',
    caught: '0',
    element: ['dragon', 'electric'],
    workSkill: [
      { skill: 'transporting', lv: '3' },
      { skill: 'generatingElectricity', lv: '4' },
      { skill: 'handiwork', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/orserk.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Shadowbeak',
    number: '107',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'gathering', lv: '1' }],
    searchFilter: '',
    image: '/pal/icon/shadowbeak.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Paladius',
    number: '108',
    caught: '0',
    element: ['neutral'],
    workSkill: [
      { skill: 'mining', lv: '2' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/paladius.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Necromus',
    number: '109',
    caught: '0',
    element: ['dark'],
    workSkill: [
      { skill: 'mining', lv: '2' },
      { skill: 'lumbering', lv: '2' },
    ],
    searchFilter: '',
    image: '/pal/icon/necromus.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Frostallion',
    number: '110',
    caught: '0',
    element: ['ice'],
    workSkill: [{ skill: 'cooling', lv: '4' }],
    searchFilter: '',
    image: '/pal/icon/frostallion.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Frostallion Noct',
    number: '110B',
    caught: '0',
    element: ['dark'],
    workSkill: [{ skill: 'gathering', lv: '4' }],
    searchFilter: '',
    image: '/pal/icon/frostallionNoct.webp',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jetragon',
    number: '111',
    caught: '0',
    element: ['dragon'],
    workSkill: [{ skill: 'gathering', lv: '3' }],
    searchFilter: '',
    image: '/pal/icon/Jetragon.webp',
  },
]

export const elements = [
  { name: 'dark', value: 'dark', srcImage: '/icon/element/dark.webp' },
  { name: 'dragon', value: 'dragon', srcImage: '/icon/element/dragon.webp' },
  {
    name: 'electric',
    value: 'electric',
    srcImage: '/icon/element/electric.webp',
  },
  { name: 'fire', value: 'fire', srcImage: '/icon/element/fire.webp' },
  { name: 'grass', value: 'grass', srcImage: '/icon/element/grass.webp' },
  { name: 'ground', value: 'ground', srcImage: '/icon/element/ground.webp' },
  { name: 'ice', value: 'ice', srcImage: '/icon/element/ice.webp' },
  { name: 'neutral', value: 'neutral', srcImage: '/icon/element/neutral.webp' },
  { name: 'water', value: 'water', srcImage: '/icon/element/water.webp' },
]

export const workSuitability = [
  { name: 'cooling', value: 'cooling', srcImage: '/icon/work/cooling.webp' },
  { name: 'farming', value: 'farming', srcImage: '/icon/work/farming.webp' },
  {
    name: 'gathering',
    value: 'gathering',
    srcImage: '/icon/work/gathering.webp',
  },
  {
    name: 'generate electricity',
    value: 'generatingElectricity',
    srcImage: '/icon/work/generatingElectricity.webp',
  },
  {
    name: 'handiwork',
    value: 'handiwork',
    srcImage: '/icon/work/handiwork.webp',
  },
  { name: 'kindling', value: 'kindling', srcImage: '/icon/work/kindling.webp' },
  {
    name: 'lumbering',
    value: 'lumbering',
    srcImage: '/icon/work/lumbering.webp',
  },
  {
    name: 'medicine production',
    value: 'medicineProduction',
    srcImage: '/icon/work/medicineProduction.webp',
  },
  { name: 'mining', value: 'mining', srcImage: '/icon/work/mining.webp' },
  { name: 'planting', value: 'planting', srcImage: '/icon/work/planting.webp' },
  {
    name: 'transporting',
    value: 'transporting',
    srcImage: '/icon/work/transporting.webp',
  },
  { name: 'watering', value: 'watering', srcImage: '/icon/work/watering.webp' },
]
